spring:
  jpa:
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        jdbc:
          batch_size: 5
        order_inserts: true
        order_updates: true
  datasource:
    url: jdbc:postgresql://${RDS_HOSTNAME:localhost}:${RDS_PORT:5432}/${RDS_DB_NAME:geren_db}?currentSchema=${RDS_SCHEMA_NAME:geren_dev}&binaryTransfer=true&reWriteBatchedInserts=true
    username: ${RDS_USERNAME:geren_main}
    password: ${RDS_PASSWORD:admin1}
    driver-class-name: org.postgresql.Driver
  cloud:
    aws:
      region:
        static: eu-central-1

calendar-events-collecting:
  calendars:
    - "primary"
    - "Testowy calendar 2"
  job:
    enabled: true
    cron: 0 0 6 * * *

calendar-events-processing:
  notification-medium: MOCK
  job:
    enabled: true
    cron: 0 0 7 * * *