spring:
  jpa:
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
  datasource:
    url: jdbc:postgresql://localhost:5432/geren_db?currentSchema=geren_dev&binaryTransfer=true&reWriteBatchedInserts=true
    username: geren_main
    password: admin1
    driver-class-name: org.postgresql.Driver
    platform: postgres
  cloud:
    aws:
      region:
        static: eu-central-1

scheduled:
  jobs:
    daily-meetings:
      enabled: true
      cron: 0 0 6 * * *

calendar-events-collecting:
  calendars:
    - "primary"
    - "Testowy calendar 2"